// ============================================================
// BENYAMIN BATAU CRYPTO GAME — DATA.JS
// All static game data: cards, recipes, research, achievements
// ============================================================

const CARDS_DB = [
  // ─── MYTHIC ───────────────────────────────────────────────
  { id:'war_machine', name:'WAR MACHINE', file:'WAR_MACHINE.py', emoji:'⚔️', rarity:6,
    category:'AI', loc:123000, unlockLv:50,
    desc:'10 strategi berjalan bersamaan. Market Regime Detector aktif. Claude = Brain, War Machine = Tangan.',
    flavor:'"Siap perang di semua kondisi pasar."',
    stats:{scanSpeed:200,prediction:95,execSpeed:150,protection:100},
    passive:'Ammo System: Active 60% | Reserve 30% | Sacred 10%. Max 3 posisi simultan.',
    special:'Market Regime: AUTO-SWITCH Trending→Ranging→Chaos→Accumulation',
    funcs:['market_regime_detector()','strategy_vote(weight)','position_sizer_kelly()','trailing_stop_dynamic()','ammo_allocator()'] },

  { id:'master_bot', name:'BENYAMIN MASTER BOT', file:'BENYAMIN_MASTER_BOT.py', emoji:'🤖', rarity:6,
    category:'Bot', loc:1012, unlockLv:60,
    desc:'Puncak dari semua bot. Aktif 08:00 & 20:00 WIB. Coiled Spring detection + Auto-Loop on TP.',
    flavor:'"Dibuat oleh Benyamin Batau, guru SMK Makassar, untuk mengubah nasib."',
    stats:{scanSpeed:180,prediction:90,execSpeed:200,protection:120},
    passive:'Coiled Spring Detector: Deteksi sleeping coin sebelum pump. Profit Multiplier 5×.',
    special:'Peak Hour: +300% Capital jam 08:00 & 20:00 WIB setiap hari.',
    funcs:['detect_sleeping_coins()','grok_analyze_candidates()','monitor_position()','is_peak_hour()','execute_buy()'] },

  // ─── LEGENDARY ────────────────────────────────────────────
  { id:'claude_brain', name:'CLAUDE BRAIN', file:'CLAUDE_BRAIN.py', emoji:'🧠', rarity:5,
    category:'AI', loc:664, unlockLv:30,
    desc:'AI Decision Engine dengan confidence scoring 0.0–1.0. Setiap keputusan dianalisis multi-turn.',
    flavor:'"Think before you trade. Always."',
    stats:{scanSpeed:100,prediction:150,execSpeed:80,protection:60},
    passive:'Decision Engine: BUY/SELL/HOLD dengan urgency NOW/WAIT/MONITOR/STOP.',
    special:'AI Cascade: Jika confidence < 0.5, otomatis HOLD untuk melindungi capital.',
    funcs:['analyze_market(snapshot)','execute_decision(d)','_parse_claude_response(txt)','run_loop()','ask(q)'] },

  { id:'sensor', name:'SENSOR.py', file:'SENSOR.py', emoji:'📡', rarity:5,
    category:'Data', loc:70000, unlockLv:25,
    desc:'Market Data Collector 4-API real-time. Scan 10 detik. News + Social + Price + Trending.',
    flavor:'"Mendengar pasar sebelum pasar berbicara."',
    stats:{scanSpeed:200,prediction:80,execSpeed:60,protection:40},
    passive:'Multi-Source: Indodax + CoinGecko + NewsAPI + LunarCrush. 2000 ticks/coin buffer.',
    special:'Regime Detector: Identifikasi Trending/Ranging/Chaos/Accumulation secara otomatis.',
    funcs:['get_summaries()','private(method,params)','detect_regime()','score_coin()','auto_execute_buy()'] },

  { id:'bot_engine_hf', name:'BOT ENGINE HF', file:'bot_engine.py', emoji:'☁️', rarity:5,
    category:'Bot', loc:731, unlockLv:35,
    desc:'Cloud-deployable trading engine untuk HuggingFace. Persistent state. Auto-recovery on crash.',
    flavor:'"Tidak pernah berhenti, bahkan saat server restart."',
    stats:{scanSpeed:120,prediction:100,execSpeed:110,protection:90},
    passive:'Cloud Persistence: State tersimpan di cloud. Recovery otomatis saat restart.',
    special:'Startup Recovery: Posisi terbuka sebelum crash otomatis dilanjutkan.',
    funcs:['run_one_cycle()','save_state_persistent()','load_state_persistent()','upload_log_to_hf()','startup_recovery()'] },

  // ─── EPIC ─────────────────────────────────────────────────
  { id:'bot_aktif', name:'BOT AKTIF', file:'bot_aktif.py', emoji:'🔥', rarity:4,
    category:'Bot', loc:26000, unlockLv:18,
    desc:'Multi-coin active bot dengan ONDO Regime Detector khusus. Dynamic exit price adjustment.',
    flavor:'"Selalu aktif. Selalu mencari peluang."',
    stats:{scanSpeed:90,prediction:70,execSpeed:100,protection:50},
    passive:'ONDO Special Mode: Deteksi regime khusus ONDO untuk akurasi lebih tinggi.',
    special:'Scan Dan Beli: Auto-scan + auto-beli saat sinyal terkonfirmasi.',
    funcs:['_ondo_regime()','scan_dan_beli(idr)','manage_posisi()','_cancel_and_sl()','_replace_ondo_sell()'] },

  { id:'claude_pro', name:'CLAUDE PRO TRADER', file:'claude_pro_trader.py', emoji:'🎯', rarity:4,
    category:'AI', loc:18000, unlockLv:20,
    desc:'Claude AI langsung memutuskan setiap trade. Persistent state antar sesi.',
    flavor:'"Bukan sekedar bot — ini partner trading berbasis AI."',
    stats:{scanSpeed:70,prediction:120,execSpeed:80,protection:70},
    passive:'AI-First Decision: Setiap buy/sell keputusan Claude langsung.',
    special:'State Memory: Ingat posisi dan keputusan sebelumnya.',
    funcs:['scan_pasar()','eksekusi_buy(selected)','load_state()','save_state()','pub_ticker()'] },

  { id:'analisis_strategi', name:'ANALISIS STRATEGI', file:'analisis_strategi.py', emoji:'📊', rarity:4,
    category:'Analysis', loc:14000, unlockLv:12,
    desc:'Technical analysis lengkap: RSI, EMA, Momentum Scoring. Coil formula dari kode nyata.',
    flavor:'"Data tidak berbohong. Interpretasi bisa salah."',
    stats:{scanSpeed:80,prediction:90,execSpeed:50,protection:40},
    passive:'Coil Formula: log(vol)×0.3 + (18-range)/18×0.4 + sideways×0.1',
    special:'Market Regime via TA: Deteksi fase pasar dari indikator teknikal.',
    funcs:['rsi_label(r)','calc_ema(prices,period)','momentum_score()','regime_detect()','coil_score()'] },

  { id:'eksekusi_analisis', name:'EKSEKUSI ANALISIS', file:'eksekusi_analisis.py', emoji:'⚡', rarity:4,
    category:'Execution', loc:14000, unlockLv:15,
    desc:'Execute AI-recommended trades dengan slippage protection. Direct ke Indodax API.',
    flavor:'"Analisis tanpa eksekusi tidak ada gunanya."',
    stats:{scanSpeed:60,prediction:60,execSpeed:150,protection:80},
    passive:'Slippage Guard: Tolak order jika harga bergerak lebih dari 2% saat eksekusi.',
    special:'Smart Execution: Pilih market vs limit berdasarkan urgency signal.',
    funcs:['private(method,params)','get_ticker(pair)','fmt(v)','smart_order()','anti_queue()'] },

  // ─── RARE ─────────────────────────────────────────────────
  { id:'emergency_close', name:'EMERGENCY CLOSE', file:'emergency_close.py', emoji:'🚨', rarity:3,
    category:'Risk', loc:8600, unlockLv:8,
    desc:'Emergency close ALL posisi sekarang. Multi-slip protection. Wajib untuk Flash Crash event.',
    flavor:'"Ketika semua gagal, ini yang menyelamatkan."',
    stats:{scanSpeed:30,prediction:20,execSpeed:200,protection:200},
    passive:'Flash Crash Shield: Saat event Flash Crash, capital terlindungi 85%.',
    special:'Force Close: Jual semua posisi dalam 1 detik game-time.',
    funcs:['market_sell_all()','cancel_all_orders()','get_open_orders()','fmt_idr()','emergency_log()'] },

  { id:'monitor_vex', name:'MONITOR VEX', file:'monitor_vex.py', emoji:'👁️', rarity:3,
    category:'Monitor', loc:6900, unlockLv:6,
    desc:'Dedicated VEX coin monitor dengan auto-sell logic dan alert real-time.',
    flavor:'"VEX tidak bisa kabur dari pengawasanku."',
    stats:{scanSpeed:70,prediction:50,execSpeed:80,protection:40},
    passive:'VEX Specialist: +50% profit dari semua trading VEX coin.',
    special:'Auto-Sell Trigger: Jual VEX otomatis jika harga menyentuh target.',
    funcs:['private(method)','ticker(pair)','auto_sell_check()','log(msg)','alert_telegram()'] },

  { id:'scanner_strategi', name:'SCANNER STRATEGI', file:'scanner_strategi.py', emoji:'🔍', rarity:3,
    category:'Analysis', loc:6300, unlockLv:10,
    desc:'Market scanner dengan regime detection untuk 500+ pair Indodax sekaligus.',
    flavor:'"Scan dulu, baru tembak."',
    stats:{scanSpeed:150,prediction:70,execSpeed:40,protection:30},
    passive:'Full Scan: Scan semua 500+ pair dalam 1 siklus.',
    special:'Regime Filter: Hanya tampilkan coin dengan regime yang menguntungkan.',
    funcs:['scan()','get_summaries()','get_ticker_detail(pair)','regime_filter()','log(msg)'] },

  { id:'monitor_ondo', name:'MONITOR ONDO', file:'monitor_ondo.py', emoji:'🔵', rarity:3,
    category:'Monitor', loc:5900, unlockLv:7,
    desc:'ONDO position monitor dengan cancel & instant market sell.',
    flavor:'"ONDO selalu bergerak. Harus selalu dipantau."',
    stats:{scanSpeed:60,prediction:45,execSpeed:90,protection:50},
    passive:'ONDO Regime: +35% profit khusus ONDO berkat regime detection spesifik.',
    special:'Cancel & Re-sell: Otomatis cancel sell lama dan pasang sell baru di harga lebih baik.',
    funcs:['cancel_and_market_sell()','ticker()','private()','load_posisi()','save_posisi()'] },

  { id:'monitor_pump', name:'MONITOR PUMP', file:'monitor_pump.py', emoji:'🚀', rarity:3,
    category:'Monitor', loc:9100, unlockLv:9,
    desc:'Monitor pump positions secara dinamis. Auto-adjust sell sesuai momentum pump.',
    flavor:'"Pump bisa datang kapan saja. Siap selalu."',
    stats:{scanSpeed:80,prediction:60,execSpeed:70,protection:35},
    passive:'Pump Detector: +40% profit saat event pump terjadi.',
    special:'Dynamic Sell: Naikkan target jual otomatis saat pump terus berlanjut.',
    funcs:['private(method)','ticker(pair)','pasang_sell()','ganti_sell()','log(msg)'] },

  { id:'analyze_trades', name:'ANALYZE TRADES', file:'analyze_trades.py', emoji:'📈', rarity:3,
    category:'Analysis', loc:4400, unlockLv:5,
    desc:'P&L analysis pada trade history. Rekonstruksi setiap transaksi untuk pembelajaran.',
    flavor:'"Belajar dari masa lalu agar lebih baik di masa depan."',
    stats:{scanSpeed:40,prediction:80,execSpeed:30,protection:60},
    passive:'Trade Memory: +20% prediksi akurasi dari analisis histori.',
    special:'Win Rate Tracker: Hitung win rate dan average profit per trade.',
    funcs:['reconstruct_trade()','calc_pnl()','win_rate()','avg_profit()','export_report()'] },

  // ─── UNCOMMON ─────────────────────────────────────────────
  { id:'monitor_link', name:'MONITOR LINK', file:'monitor_link.py', emoji:'🔗', rarity:2,
    category:'Monitor', loc:8100, unlockLv:4,
    desc:'Dedicated LINK coin monitor dengan persistent position state.',
    flavor:'"LINK = Chainlink. Pemain kecil bisa ikut untung besar."',
    stats:{scanSpeed:50,prediction:35,execSpeed:60,protection:40},
    passive:'LINK Tracker: +20% profit dari trading LINK.',
    special:'Persistent Position: Posisi LINK tidak hilang meski bot restart.',
    funcs:['private()','ticker_link()','load_posisi()','save_posisi()','log()'] },

  { id:'monitor_pippin', name:'MONITOR PIPPIN', file:'monitor_pippin.py', emoji:'🎪', rarity:2,
    category:'Monitor', loc:8500, unlockLv:4,
    desc:'PIPPIN position monitor dengan stop-loss detection dan dynamic replace sell.',
    flavor:'"PIPPIN kecil tapi bisa bawa profit besar."',
    stats:{scanSpeed:45,prediction:30,execSpeed:65,protection:55},
    passive:'PIPPIN SL Guard: Stop loss otomatis dengan 3% trailing.',
    special:'Replace Sell: Ganti order sell secara otomatis di harga lebih optimal.',
    funcs:['sl_sell(id,amt)','replace_sell(old,new,price)','ticker()','private()'] },

  { id:'pantau_posisi', name:'PANTAU POSISI', file:'pantau_posisi.py', emoji:'👀', rarity:2,
    category:'Monitor', loc:8800, unlockLv:3,
    desc:'Monitor semua posisi aktif secara holistic dalam satu tampilan.',
    flavor:'"Lihat semuanya sekaligus. Tidak ada yang lolos."',
    stats:{scanSpeed:60,prediction:40,execSpeed:40,protection:45},
    passive:'Overview Mode: Lihat semua coin sekaligus.',
    special:'Portfolio Snapshot: Generate laporan posisi real-time.',
    funcs:['private()','log()','track_all_positions()','portfolio_summary()'] },

  { id:'jual_paksa', name:'JUAL PAKSA SEMUA', file:'jual_paksa_semua.py', emoji:'💸', rarity:2,
    category:'Execution', loc:11000, unlockLv:5,
    desc:'Force-sell ALL posisi di harga pasar. Digunakan saat situasi kritis.',
    flavor:'"Terkadang lebih baik rugi kecil dari pada rugi besar."',
    stats:{scanSpeed:20,prediction:10,execSpeed:200,protection:100},
    passive:'Panic Sell: Jual semua dalam hitungan detik game-time.',
    special:'Partial Protection: Simpan 10% balance untuk trade berikutnya.',
    funcs:['private()','ticker(pair)','fmt(v)','force_market_sell_all()'] },

  // ─── COMMON ───────────────────────────────────────────────
  { id:'cek_status', name:'CEK STATUS', file:'cek_status.py', emoji:'✅', rarity:1,
    category:'Utility', loc:3300, unlockLv:1,
    desc:'Script pertama. Check account status dan open orders. Awal dari segalanya.',
    flavor:'"Semua perjalanan dimulai dari satu langkah."',
    stats:{scanSpeed:10,prediction:5,execSpeed:10,protection:5},
    passive:'Basic Monitor: +5% efisiensi semua bot.',
    special:null,
    funcs:['private(method)','parse_orders(resp)','display_status()'] },

  { id:'poll_saldo', name:'POLL SALDO', file:'poll_saldo.py', emoji:'💵', rarity:1,
    category:'Utility', loc:2200, unlockLv:1,
    desc:'Poll current balance dari Indodax API secara berkala.',
    flavor:'"Tahu saldo adalah fondasi semua keputusan."',
    stats:{scanSpeed:15,prediction:5,execSpeed:5,protection:10},
    passive:'Balance Aware: +10% Capital production saat balance tinggi.',
    special:null,
    funcs:['call(method,params)','display_balance()'] },

  { id:'check_pond', name:'CHECK POND', file:'check_pond.py', emoji:'🐸', rarity:1,
    category:'Utility', loc:1200, unlockLv:1,
    desc:'Quick POND balance check. Script yang menemukan profit Rp127rb yang terlupakan.',
    flavor:'"Coin kecil pun punya nilai. Jangan dilupakan."',
    stats:{scanSpeed:8,prediction:8,execSpeed:8,protection:8},
    passive:'Hidden Profit: 2% chance menemukan "hidden capital" tiap menit.',
    special:null,
    funcs:['check_balance()','display_pond()'] },

  { id:'cek_history', name:'CEK HISTORY', file:'cek_history.py', emoji:'📜', rarity:1,
    category:'Utility', loc:3400, unlockLv:1,
    desc:'View trade history dan rekonstruksi P&L dari semua transaksi.',
    flavor:'"Historia magistra vitae. Sejarah adalah guru kehidupan."',
    stats:{scanSpeed:5,prediction:15,execSpeed:5,protection:15},
    passive:'History Wisdom: +15% Research Point dari setiap trade.',
    special:null,
    funcs:['private()','tampil_orders(orders,coin)','calc_history_pnl()'] },

  { id:'beli_pump', name:'BELI PUMP', file:'beli_pump.py', emoji:'📈', rarity:1,
    category:'Strategy', loc:5200, unlockLv:2,
    desc:'Strategi beli saat pump detection. Dasar dari pump strategy.',
    flavor:'"Masuk saat momentum. Keluar sebelum terlambat."',
    stats:{scanSpeed:20,prediction:20,execSpeed:20,protection:10},
    passive:'Pump Entry: +10% profit saat beli di fase pump.',
    special:null,
    funcs:['private()','ticker(pair)','detect_pump()','execute_pump_buy()'] },

  { id:'scan_pump', name:'SCAN PUMP', file:'scan_pump.py', emoji:'🔎', rarity:1,
    category:'Analysis', loc:4200, unlockLv:2,
    desc:'Scan seluruh market untuk coin yang sedang atau akan pump.',
    flavor:'"Temukan gelombang sebelum surfer lain."',
    stats:{scanSpeed:35,prediction:25,execSpeed:10,protection:5},
    passive:'Early Pump Signal: +25% chance mendeteksi pump lebih awal.',
    special:null,
    funcs:['summaries()','detect_volume_spike()','rank_pumps()'] },

  { id:'ubah_target', name:'UBAH TARGET', file:'ubah_target.py', emoji:'🎯', rarity:1,
    category:'Execution', loc:3600, unlockLv:2,
    desc:'Modify target harga open orders. Fleksibilitas dalam manajemen posisi.',
    flavor:'"Target bisa diubah. Tapi jangan ubah strategi saat panik."',
    stats:{scanSpeed:10,prediction:10,execSpeed:30,protection:20},
    passive:'Flexible Target: Cancel & re-sell di harga lebih optimal.',
    special:null,
    funcs:['private()','parse_orders()','cancel_and_resell(pair,price)'] },
];

// ─── CRAFTING RECIPES ─────────────────────────────────────────
const RECIPES = [
  { id:'trend_detector', name:'Trend Detector', emoji:'📉',
    rarity:3, ingredients:['scan_pump','cek_status'],
    desc:'Deteksi tren pasar dari kombinasi pump scan + status check.',
    bonus:'Trend Detection +30%', capital:2000 },

  { id:'smart_scanner', name:'Smart Scanner', emoji:'🔬',
    rarity:3, ingredients:['scanner_strategi','analyze_trades'],
    desc:'Scanner cerdas yang belajar dari histori trade.',
    bonus:'Scan Accuracy +50%', capital:5000 },

  { id:'position_guardian', name:'Position Guardian', emoji:'🛡️',
    rarity:4, ingredients:['emergency_close','pantau_posisi'],
    desc:'Guardian posisi: pantau dan siap tutup darurat kapanpun.',
    bonus:'Capital Protection +100%', capital:15000 },

  { id:'pump_hunter', name:'Pump Hunter', emoji:'🏹',
    rarity:4, ingredients:['monitor_pump','beli_pump','scan_pump'],
    desc:'Tiga komponen pump menjadi satu mesin berburu pump.',
    bonus:'Pump Profit +80%', capital:25000 },

  { id:'ondo_master', name:'ONDO Master', emoji:'🔵',
    rarity:4, ingredients:['monitor_ondo','bot_aktif'],
    desc:'Kuasai trading ONDO dengan monitoring + active bot.',
    bonus:'ONDO Profit +120%', capital:30000 },

  { id:'multi_monitor', name:'Multi Monitor', emoji:'🖥️',
    rarity:4, ingredients:['monitor_vex','monitor_link','monitor_pippin'],
    desc:'Monitor VEX, LINK, dan PIPPIN sekaligus dalam satu sistem.',
    bonus:'Monitor Efficiency +90%', capital:20000 },

  { id:'analysis_engine', name:'Analysis Engine', emoji:'🧮',
    rarity:4, ingredients:['analisis_strategi','eksekusi_analisis'],
    desc:'Analisis + eksekusi dalam satu engine terintegrasi.',
    bonus:'Trade Accuracy +70%', capital:35000 },

  { id:'ai_core', name:'AI Core', emoji:'🤖',
    rarity:5, ingredients:['claude_brain','sensor'],
    desc:'Otak AI + sensor data menjadi sistem keputusan terpadu.',
    bonus:'AI Decision Power +200%', capital:100000 },

  { id:'cloud_trader', name:'Cloud Trader', emoji:'☁️',
    rarity:5, ingredients:['bot_engine_hf','claude_pro'],
    desc:'Cloud-based AI trader yang tidak pernah berhenti.',
    bonus:'Uptime +100%, Capital +150%', capital:150000 },

  { id:'trading_trinity', name:'Trading Trinity', emoji:'🌟',
    rarity:5, ingredients:['bot_aktif','analisis_strategi','emergency_close'],
    desc:'Tiga pilar trading: aksi, analisis, perlindungan.',
    bonus:'Overall +200%', capital:200000 },

  { id:'quantum_proto', name:'Quantum Prototype', emoji:'⚛️',
    rarity:6, ingredients:['war_machine','ai_core'],
    desc:'Gabungan War Machine + AI Core = proto quantum trading.',
    bonus:'ALL STATS +500%', capital:1000000 },
];

// ─── RESEARCH TREE ────────────────────────────────────────────
const RESEARCH_DATA = [
  { branch:'📊 Market Analysis', color:'#00e5ff', nodes:[
    { id:'rsi',     name:'RSI Analyzer',      icon:'📈', cost:50,    bonus:'+10% Detection',        req:null,     lvReq:1 },
    { id:'macd',    name:'MACD Engine',        icon:'📉', cost:150,   bonus:'+15% Trend',            req:'rsi',    lvReq:3 },
    { id:'bb',      name:'Bollinger Band',     icon:'〰️', cost:300,   bonus:'+20% Volatility',       req:'macd',   lvReq:6 },
    { id:'ema',     name:'EMA Cross',          icon:'📊', cost:600,   bonus:'+25% Confirm',          req:'bb',     lvReq:10 },
    { id:'vwap',    name:'VWAP Tracker',       icon:'💹', cost:1200,  bonus:'+30% Timing',           req:'ema',    lvReq:15 },
    { id:'coiled',  name:'Coiled Spring',      icon:'🌀', cost:3000,  bonus:'+100% Sleeping Coin',   req:'vwap',   lvReq:20 },
  ]},
  { branch:'⚡ Execution System', color:'#00ff88', nodes:[
    { id:'ws',      name:'Websocket Engine',   icon:'🔌', cost:200,   bonus:'+20% Realtime',         req:null,     lvReq:2 },
    { id:'router',  name:'Order Router',       icon:'🔄', cost:500,   bonus:'+30% Speed',            req:'ws',     lvReq:5 },
    { id:'smart_ex',name:'Smart Execution',    icon:'🎯', cost:1200,  bonus:'+40% Slippage Ctrl',    req:'router', lvReq:10 },
    { id:'hmac',    name:'HMAC API Signer',    icon:'🔐', cost:2500,  bonus:'+50% Security',         req:'smart_ex',lvReq:15 },
    { id:'hft',     name:'High Speed Trading', icon:'⚡', cost:8000,  bonus:'+100% Trade Speed',     req:'hmac',   lvReq:25 },
    { id:'anti_q',  name:'Anti-Queue Order',   icon:'🚀', cost:20000, bonus:'Zero Slippage Mode',    req:'hft',    lvReq:35 },
  ]},
  { branch:'🛡️ Risk Management', color:'#ff00aa', nodes:[
    { id:'sl',      name:'Stop Loss',          icon:'🛑', cost:100,   bonus:'+20% Protection',       req:null,     lvReq:1 },
    { id:'tp',      name:'Take Profit',        icon:'🎯', cost:150,   bonus:'+25% Lock',             req:'sl',     lvReq:2 },
    { id:'trailing',name:'Trailing SL',        icon:'📐', cost:800,   bonus:'Dynamic SL ±5/8/15/25%',req:'tp',     lvReq:8 },
    { id:'kelly',   name:'Kelly Sizing',       icon:'📏', cost:3000,  bonus:'Optimal Position Size', req:'trailing',lvReq:15 },
    { id:'ammo',    name:'Ammo Management',    icon:'💣', cost:10000, bonus:'60/30/10 Allocation',   req:'kelly',  lvReq:25 },
    { id:'hedge',   name:'Hedging System',     icon:'⚖️', cost:30000, bonus:'Risk Correlation -40%', req:'ammo',   lvReq:40 },
  ]},
  { branch:'🤖 Artificial Intelligence', color:'#9d4edd', nodes:[
    { id:'neural',  name:'Neural Network',     icon:'🧬', cost:5000,  bonus:'+50% Pattern Recog',    req:null,     lvReq:20 },
    { id:'ml',      name:'Machine Learning',   icon:'🔮', cost:10000, bonus:'+75% Adaptive',         req:'neural', lvReq:28 },
    { id:'grok_ai', name:'Grok AI Link',       icon:'✨', cost:15000, bonus:'call_grok +100%',       req:'ml',     lvReq:35 },
    { id:'claude_ai',name:'Claude AI Brain',   icon:'🧠', cost:25000, bonus:'Multi-turn +150%',      req:'grok_ai',lvReq:42 },
    { id:'deep_l',  name:'Deep Learning',      icon:'🌊', cost:50000, bonus:'+200% Complex Pattern', req:'claude_ai',lvReq:55 },
    { id:'quantum_ai',name:'Quantum AI',       icon:'🌌', cost:150000,bonus:'Profit Multiplier 5×',  req:'deep_l', lvReq:75 },
  ]},
  { branch:'📡 Data Infrastructure', color:'#ffd700', nodes:[
    { id:'tele',    name:'Telegram Notif',     icon:'📱', cost:300,   bonus:'Real-time Alerts',      req:null,     lvReq:5 },
    { id:'hf_sync', name:'HuggingFace Sync',   icon:'🤗', cost:6000,  bonus:'Cloud Persistent State',req:'tele',   lvReq:20 },
    { id:'news_api',name:'NewsAPI Feed',       icon:'📰', cost:8000,  bonus:'+30% Sentiment',        req:'hf_sync',lvReq:25 },
    { id:'lunar',   name:'LunarCrush Social',  icon:'🌙', cost:12000, bonus:'+25% Social Signal',    req:'news_api',lvReq:30 },
    { id:'gecko',   name:'CoinGecko Trending', icon:'🦎', cost:15000, bonus:'+20% Trend Data',       req:'lunar',  lvReq:35 },
    { id:'multi_src',name:'Multi-Source AI',   icon:'🕸️', cost:40000, bonus:'All 4 API × Synergy',  req:'gecko',  lvReq:50 },
  ]},
];

// ─── BOSS DATA ────────────────────────────────────────────────
const BOSSES = [
  { id:'whale_king', name:'The Whale King', emoji:'🐋', hp:100000,
    reward:'Legendary card guaranteed', drop:'sensor',
    attack:'Volume Manipulation: Capital -20% per hit',
    weakTo:'emergency_close,analisis_strategi',
    lore:'Whale King adalah manipulator terbesar di Indodax. Dia bisa menggerakkan harga sesuka hati. Tapi tidak ada yang tidak bisa dikalahkan dengan strategi yang tepat.' },
  { id:'market_manip', name:'Market Manipulator', emoji:'💀', hp:500000,
    reward:'Epic card × 3', drop:'analisis_strategi',
    attack:'Fake Pump: Menjebak kamu beli di puncak.',
    weakTo:'scanner_strategi,claude_brain',
    lore:'Market Manipulator adalah entitas misterius yang menciptakan sinyal palsu. Hanya analisis mendalam yang bisa menembus tipuannya.' },
  { id:'flash_titan', name:'Flash Crash Titan', emoji:'💥', hp:1000000,
    reward:'Mythic card chance 50%', drop:'war_machine',
    attack:'Flash Crash: Capital -50% dalam 1 hit.',
    weakTo:'war_machine,master_bot',
    lore:'Flash Crash Titan adalah manifestasi dari ketakutan terbesar setiap trader: crash tiba-tiba yang menghancurkan semua posisi. Hanya bot terkuat yang bisa bertahan.' },
];

// ─── ACHIEVEMENTS ─────────────────────────────────────────────
const ACHIEVEMENTS = [
  { id:'first_script', name:'Script Pertama', emoji:'💡', desc:'Dapatkan kartu pertamamu', reward:'500 Capital', condition: s => s.ownedCards.length >= 1 },
  { id:'first_million', name:'Jutawan Pertama', emoji:'💰', desc:'Capital mencapai Rp 1,000,000', reward:'Data Pack', condition: s => s.totalCapitalEarned >= 1000000 },
  { id:'first_craft', name:'Programmer Sejati', emoji:'⚒️', desc:'Craft kartu pertamamu', reward:'10 Research Points', condition: s => s.totalCrafts >= 1 },
  { id:'beat_whale', name:'Pembunuh Whale', emoji:'🐋', desc:'Kalahkan The Whale King', reward:'Legendary Card', condition: s => s.bossesKilled.includes('whale_king') },
  { id:'collector_10', name:'Script Nerd', emoji:'📚', desc:'Kumpulkan 10 kartu berbeda', reward:'20 AI Token', condition: s => s.ownedCards.length >= 10 },
  { id:'collector_all_common', name:'Common Master', emoji:'⚪', desc:'Kumpulkan semua kartu Common', reward:'Rare Pack', condition: s => ['cek_status','poll_saldo','check_pond','cek_history','beli_pump','scan_pump','ubah_target'].every(id => s.ownedCards.includes(id)) },
  { id:'researcher', name:'Peneliti Muda', emoji:'🔬', desc:'Unlock 5 research nodes', reward:'2000 Capital', condition: s => s.unlockedResearch.size >= 5 },
  { id:'ai_researcher', name:'AI Master', emoji:'🤖', desc:'Unlock Claude AI node', reward:'50 AI Token', condition: s => s.unlockedResearch.has('claude_ai') },
  { id:'peak_warrior', name:'Peak Hour Warrior', emoji:'⚡', desc:'Login saat Peak Hour (08:00/20:00)', reward:'+10% permanent', condition: s => s.peakHourLogins >= 1 },
  { id:'billionaire', name:'Billionaire Club', emoji:'🏆', desc:'Total capital earned Rp 1 Billion', reward:'Epic Pack × 3', condition: s => s.totalCapitalEarned >= 1000000000 },
  { id:'survivor', name:'Flash Crash Survivor', emoji:'🚨', desc:'Survive Flash Crash event', reward:'Special card', condition: s => s.flashCrashSurvived >= 1 },
  { id:'crafter_5', name:'Forge Master', emoji:'🔨', desc:'Craft 5 kartu berbeda', reward:'Rare Pack', condition: s => s.totalCrafts >= 5 },
  { id:'level_10', name:'Veteran Trader', emoji:'🎖️', desc:'Capai Level 10', reward:'Epic Card', condition: s => s.level >= 10 },
  { id:'level_25', name:'Elite Trader', emoji:'🥇', desc:'Capai Level 25', reward:'Legendary Pack', condition: s => s.level >= 25 },
  { id:'quantum_ready', name:'Quantum Ready', emoji:'⚛️', desc:'Capai Level 50', reward:'Mythic Frame + Bonus', condition: s => s.level >= 50 },
  { id:'legendary_owner', name:'AI Prophet', emoji:'🌟', desc:'Dapatkan CLAUDE BRAIN', reward:'50 AI Token', condition: s => s.ownedCards.includes('claude_brain') },
  { id:'mythic_owner', name:'War Lord', emoji:'⚔️', desc:'Dapatkan WAR MACHINE', reward:'Exclusive Frame', condition: s => s.ownedCards.includes('war_machine') },
  { id:'daily_7', name:'Disiplin 7 Hari', emoji:'📅', desc:'Login 7 hari berturut-turut', reward:'Epic Pack', condition: s => s.loginStreak >= 7 },
  { id:'daily_30', name:'Dedikasi Sebulan', emoji:'📆', desc:'Login 30 hari berturut-turut', reward:'Legendary Pack + 50 AI Token', condition: s => s.loginStreak >= 30 },
  { id:'max_infra', name:'Quantum Corp CEO', emoji:'🏢', desc:'Capai infrastruktur Quantum Computer', reward:'Exclusive CEO Badge', condition: s => s.infraLevel >= 5 },
];

// ─── CHAPTERS / STORY ─────────────────────────────────────────
const CHAPTERS = [
  { id:1, title:'The Sleeping Coder', emoji:'💻', unlockLv:1,
    story:'Makassar, 2024. Kamu mewarisi USB drive dari Benyamin Batau — seorang guru SMK yang bermimpi besar. Di dalamnya: 5 script Python sederhana dan sebuah catatan kecil: "Mulai dari sini."',
    reward:'5 Common Cards' },
  { id:2, title:'First Signal', emoji:'📡', unlockLv:5,
    story:'Script `cek_status.py` kamu pertama kali jalan dan menemukan profit Rp127,000 dari coin POND yang terlupakan! Signal pertama dari pasar: modal kecil pun bisa tumbuh.',
    reward:'Rare Card + 5,000 Capital' },
  { id:3, title:'The Brain Awakens', emoji:'🧠', unlockLv:15,
    story:'CLAUDE_BRAIN.py berhasil diaktifkan. Untuk pertama kalinya, AI merekomendasikan BUY pada ONDO — dan dalam 3 hari, +28%. Ini bukan keberuntungan. Ini teknologi.',
    reward:'CLAUDE BRAIN Card (Guaranteed)' },
  { id:4, title:'War Machine Rising', emoji:'⚔️', unlockLv:30,
    story:'WAR_MACHINE.py online. 10 strategi berjalan bersamaan. Market Regime Detector mengidentifikasi Bull Run yang akan datang. Tapi kemudian — The Whale King muncul.',
    reward:'WAR MACHINE Card (Guaranteed)' },
  { id:5, title:'Quantum Ascension', emoji:'⚛️', unlockLv:50,
    story:'Quantum Trading Corporation berdiri. Nama Benyamin Batau bergema di seluruh dunia crypto. Tapi satu tantangan terakhir menunggu: Flash Crash Titan — kehancuran terbesar yang pernah ada.',
    reward:'Exclusive Quantum Frame + 500 AI Token' },
];

// ─── INFRASTRUCTURE ───────────────────────────────────────────
const INFRA_LEVELS = [
  { name:'Laptop Bekas', icon:'💻', rateBase:500, botSlots:1, cost:0, lvReq:1,
    desc:'Laptop tua Rp800ribu. Layar retak, tapi masih bisa jalan Python.' },
  { name:'Laptop Gaming', icon:'🎮', rateBase:3000, botSlots:3, cost:500000, lvReq:5,
    desc:'Upgrade pertama. RAM 16GB, bisa jalankan 3 bot sekaligus.' },
  { name:'PC Workstation', icon:'🖥️', rateBase:15000, botSlots:5, cost:5000000, lvReq:10,
    desc:'Workstation profesional. 6 core CPU, trading 24/7.' },
  { name:'Server Farm', icon:'🏗️', rateBase:80000, botSlots:10, cost:50000000, lvReq:25,
    desc:'Rack server pertama. Bandwidth gigabit, latency sub-10ms.' },
  { name:'GPU Cluster', icon:'⚡', rateBase:500000, botSlots:20, cost:500000000, lvReq:50,
    desc:'Cluster GPU untuk AI inference real-time. 1000x lebih cepat dari CPU.' },
  { name:'Quantum Computer', icon:'🔮', rateBase:5000000, botSlots:99, cost:9999999999, lvReq:75,
    desc:'Quantum computer. Komputasi di luar batas. The final form.' },
];

// ─── DAILY REWARDS ────────────────────────────────────────────
const DAILY_REWARDS = [
  { day:1,  type:'capital',  amount:5000,    label:'Rp 5.000' },
  { day:2,  type:'capital',  amount:10000,   label:'Rp 10.000 + 50 DM' },
  { day:3,  type:'pack',     pack:'common',  label:'Common Pack' },
  { day:4,  type:'capital',  amount:50000,   label:'Rp 50.000' },
  { day:5,  type:'pack',     pack:'rare',    label:'Rare Pack' },
  { day:6,  type:'aitoken',  amount:5,       label:'5 AI Token' },
  { day:7,  type:'pack',     pack:'epic',    label:'Epic Pack + 100K', bonus:100000 },
  { day:14, type:'pack',     pack:'legendary',label:'Legendary Pack' },
  { day:30, type:'special',  label:'Legendary Pack + 50 AI Token', capital:500000, aiToken:50 },
];

// ─── MARKET COINS for simulation ─────────────────────────────
const MARKET_COINS = [
  { id:'vex',  name:'VEX',  color:'#00e5ff', basePrice:2500 },
  { id:'ondo', name:'ONDO', color:'#00ff88', basePrice:5000 },
  { id:'xrp',  name:'XRP',  color:'#3498db', basePrice:8500 },
  { id:'link', name:'LINK', color:'#9d4edd', basePrice:180000 },
  { id:'pippin',name:'PIPPIN',color:'#ff00aa',basePrice:1200 },
  { id:'btc',  name:'BTC',  color:'#ffd700', basePrice:1600000000 },
];
